spring:
  datasource:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: on
  data:
    redis:
      host: localhost
      port: 6386
      database: 0

custom:
  location: "http://localhost:8080"
